/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSendTradepileRouteImport } from './routes/api/send-tradepile'
import { Route as ApiLogSalesRouteImport } from './routes/api/log-sales'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendTradepileRoute = ApiSendTradepileRouteImport.update({
  id: '/api/send-tradepile',
  path: '/api/send-tradepile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogSalesRoute = ApiLogSalesRouteImport.update({
  id: '/api/log-sales',
  path: '/api/log-sales',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/log-sales': typeof ApiLogSalesRoute
  '/api/send-tradepile': typeof ApiSendTradepileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/log-sales': typeof ApiLogSalesRoute
  '/api/send-tradepile': typeof ApiSendTradepileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/log-sales': typeof ApiLogSalesRoute
  '/api/send-tradepile': typeof ApiSendTradepileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/api/log-sales' | '/api/send-tradepile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/api/log-sales' | '/api/send-tradepile'
  id: '__root__' | '/' | '/dashboard' | '/api/log-sales' | '/api/send-tradepile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ApiLogSalesRoute: typeof ApiLogSalesRoute
  ApiSendTradepileRoute: typeof ApiSendTradepileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-tradepile': {
      id: '/api/send-tradepile'
      path: '/api/send-tradepile'
      fullPath: '/api/send-tradepile'
      preLoaderRoute: typeof ApiSendTradepileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/log-sales': {
      id: '/api/log-sales'
      path: '/api/log-sales'
      fullPath: '/api/log-sales'
      preLoaderRoute: typeof ApiLogSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ApiLogSalesRoute: ApiLogSalesRoute,
  ApiSendTradepileRoute: ApiSendTradepileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
